version: "3.8"
services:
  db:
    image: ankane/pgvector
    container_name: pgvector_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medquad
    ports:
      - "5432:5432"  # Makes it accessible from your local Python script
